In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Machine Learning — Complete Notes (Markdown)

## 1. What is Machine Learning?

**Traditional Programming:**
```
Data + Rules (Program) → Output
```
A human writes explicit rules. The program follows those fixed rules no matter what.

**Machine Learning:**
```
Data + Output (answers) → Machine learns the Rules
```
Instead of writing rules by hand, we feed the machine data + the desired output (answers). The machine understands patterns, learns the relationship, and produces its own rule-set (a trained model) — which it then uses to predict answers for new, unseen data.

---

## 2. All 4 Types of Machine Learning

### 2.1 Supervised Learning
**Definition:** Learning from labeled data (input + correct output) to predict an answer for new input.

**Flow:**
```
Input + Output → Model → Learn Pattern → New Input → Predicted Output
```

**Example:** Area + Bedrooms → Price (Area and Bedrooms are features; Price is the target)

**Main types:**
- **Regression** — predicts a number. Examples: house price, salary, temperature, stock price.
- **Classification** — predicts a category. Examples: spam/not spam, pass/fail, cat/dog, fraud/not fraud.

**Common algorithms:** Linear Regression, Logistic Regression, Decision Tree, Random Forest, KNN, SVM, Naive Bayes.

### 2.2 Unsupervised Learning
**Definition:** Finding hidden patterns or groups in unlabeled data (no target/answer column).

**Flow:**
```
Input Data → ML Model → Find Patterns → Groups / Relationships
```

**Main types:**
- **Clustering** — groups similar data. Example: customer segmentation. Algorithms: K-Means, Hierarchical Clustering, DBSCAN.
- **Dimensionality Reduction** — reduces number of features while keeping important information. Uses: visualization, faster training, removing unnecessary features. Example: PCA.

### 2.3 Semi-Supervised Learning
**Definition:** Learning from a small amount of labeled data and a large amount of unlabeled data — a combination of supervised + unsupervised.

**Flow:**
```
Small Labeled Data + Large Unlabeled Data → ML Model
```

**Example:** 1,000 labeled images + 9,000 unlabeled images. Useful because labeling every example is expensive and time-consuming.

**Uses:** image classification, speech recognition, medical image analysis, web page classification.

### 2.4 Reinforcement Learning
**Definition:** Learning the best actions through rewards and penalties — an agent learns by interacting with an environment via trial and error.

**Flow:**
```
Environment → Agent → Action → Environment → Reward / Penalty → Agent learns
```

**Important terms:**
- **Agent** — the learner/decision maker (game AI, robot, self-driving system)
- **Environment** — the world the agent operates in
- **Action** — what the agent does (move, brake, accelerate, turn)
- **Reward** — positive feedback for a good action
- **Penalty** — negative feedback for a bad action
- **State** — the current situation of the environment

**Example:** Tesla self-driving car — tries an action, gets rewarded for good driving or penalized for mistakes, improves its policy over time.

### Comparison of All 4 Types

| Type | Data Given | Main Goal | Example |
|---|---|---|---|
| Supervised | Input + Output | Predict answer | House price |
| Unsupervised | Input only | Find patterns/groups | Customer groups |
| Semi-Supervised | Some labeled + lots unlabeled | Learn with limited labels | Image classification |
| Reinforcement | Actions + rewards/penalties | Learn best actions | Game / robot |

### Easy Way to Remember
1. Supervised → Teacher gives Questions + Answers
2. Unsupervised → No Teacher; find patterns yourself
3. Semi-Supervised → Little Teacher + Lots of Data
4. Reinforcement → Learn from Rewards + Penalties

### Real-Life Analogy
- **Supervised:** Teacher gives questions + correct answers; student learns and answers a new question.
- **Unsupervised:** Teacher gives many objects; student creates groups based on similarity.
- **Semi-Supervised:** Teacher explains a few examples, then the student learns from many other examples.
- **Reinforcement:** Student tries something; correct → reward, wrong → penalty; student learns from experience.

### Important Differences
- **Supervised vs Unsupervised:** Supervised has a target and predicts it; unsupervised has no target and finds patterns.
- **Supervised vs Reinforcement:** Supervised has correct answers in the training data; reinforcement learns from rewards/penalties.
- **Unsupervised vs Semi-Supervised:** Unsupervised uses no labeled data; semi-supervised uses a small amount of labeled data plus lots of unlabeled data.

### Complete ML Types Tree
```
MACHINE LEARNING
│
├── Supervised ──┬── Regression
│                └── Classification
│
├── Unsupervised ──┬── Clustering
│                   └── Dimensionality Reduction
│
├── Semi-Supervised (little labeled + lots unlabeled)
│
+── Reinforcement
     Agent → Action → Environment → Reward/Penalty → Learn
```

### One-Line Definitions
- **Supervised:** Learning from labeled data to predict an output.
- **Unsupervised:** Finding hidden patterns or groups in unlabeled data.
- **Semi-Supervised:** Learning from a small amount of labeled data and a large amount of unlabeled data.
- **Reinforcement:** Learning the best actions through rewards and penalties.

---

## 3. Machine Learning Life Cycle (12 Steps)

*Example project used throughout: "Build an AI to predict stock market prices."*

1. **Problem Statement / Project Definition** — define exactly what you want to solve.
2. **Data Collection** — gather data. Sources: **Kaggle** (public datasets), **APIs**, **web scraping**, internal databases.
3. **Data Preprocessing (Cleaning)** — remove duplicate records, handle/replace null values, fix or remove irrelevant/incorrect entries, handle outliers.
4. **Feature Engineering** — add, modify, or remove columns to make data more useful. Example: extracting "day of week" from a date column.
5. **Train-Test Split** — commonly 80% training, 20% testing.
6. **Model Selection** — choose an algorithm (Linear Regression, Decision Tree, Random Forest, Neural Network, etc.)
7. **Model Training** — feed the training data (80%) so the model learns by adjusting internal parameters to minimize error.
8. **Model Evaluation / Accuracy Check** — test on the remaining 20% (unseen data).
9. **Hyperparameter Tuning** — test different pre-training settings (e.g., learning rate, number of trees, k value) to find the best combination.

> *Everything up to this point typically happens locally. From here on, it moves toward a live/production server.*

10. **Deployment** — make the model available for live use: wrap in an **API**, set up **CI/CD**, host on cloud (**AWS**, **Render**, etc.)
11. **Monitoring** — continuously track model performance and incoming live data for issues like performance drops or data drift.
12. **Retraining** — periodically update/retrain the model with new data so it stays accurate.

---

## 4. Dataset & Core Data Concepts

```
ML = Data + Algorithm
```

Every dataset splits into:
- **Features (Independent variables / Input / X)** — the "questions," columns used to predict something.
- **Target (Dependent variable / Output / Label / y)** — the column you're trying to predict.

**Example:**

| Sname | Marks | Attendance | Result |
|-------|-------|------------|--------|
| Rahul | 85    | 90%        | Pass   |

`Sname`, `Marks`, `Attendance` = features. `Result` = target.

### Types of Data

| Type | Description | Examples |
|------|-------------|----------|
| **Structured Data** | Organized in rows & columns, fixed schema | Excel, CSV, MySQL (tables) |
| **Unstructured Data** | No fixed format | Images, text, Word docs, PDFs, videos — stored in MongoDB, Redis |
| **Semi-Structured Data** | Some structure/tags but not a strict table | JSON (key-value, APIs), XML (`<name>Rahul</name>`) |

---

## 5. Data Preprocessing (Detailed)

- **Missing values** — fill with mean/median/mode, or drop rows/columns
- **Null values** — identify and handle appropriately
- **Duplicates** — identify and remove repeated rows
- **Outliers** — data points far outside the normal range; detect using IQR (Interquartile Range) or Z-score, then remove/cap/transform

---

## 6. Encoding

Algorithms understand numbers, not text — encoding converts text into numeric form.

- **Label Encoding** — assigns each category a number. Example: `Red = 0, Green = 1, Blue = 2`.
  ⚠️ Can accidentally imply order/ranking where none exists.
- **One-Hot Encoding** — creates a separate binary (0/1) column per category, avoiding false ordering.
  Example: `Red → [1,0,0]`, `Green → [0,1,0]`, `Blue → [0,0,1]`

---

## 7. Feature Scaling

Different features have different ranges (Age: 0–100 vs Salary: 0–1,000,000). Scaling brings all features to a comparable range.

- **Normalization (Min-Max Scaling)** — rescales values to 0–1.
- **Standardization (Z-score Scaling)** — rescales so mean = 0, standard deviation = 1.

---

## 8. Prediction, Accuracy, Loss, Epoch, Learning Rate

- **Prediction** — the output the model produces for a given input.
- **Accuracy** — how often the model's predictions match true values.
- **Loss** — the difference between actual and predicted value.
  ```
  Loss = Actual Value − Predicted Value
  ```
- **Epoch** — one complete pass of the entire training dataset through the algorithm.
  Example: 100 rows, epoch = 3 → the model goes through all 100 rows 3 times.
- **Learning Rate** — how big a step the model takes when updating itself to reduce error.
  - Too high → may overshoot, unstable, fails to converge.
  - Too low → learns very slowly.

---

## 9. Supervised Learning: Regression vs Classification

| | Regression | Classification |
|---|---|---|
| Predicts | Continuous numeric values | Discrete categories |
| Example | House price, stock price, temperature | Spam/not spam, pass/fail |
| Common Algorithms | Linear Regression, Polynomial Regression | Logistic Regression, Decision Tree, KNN, SVM |

### Types of Regression

- **Simple Linear Regression** — one input feature predicts one output:
  ```
  y = mx + c
  ```
  - `y` = predicted output
  - `x` = input feature
  - `m` = slope (learned)
  - `c` = intercept (learned)

- **Multiple Linear Regression** — multiple inputs predict one output:
  ```
  y = m1x1 + m2x2 + ... + mnxn + c
  ```

- **Polynomial Regression** — models curved/non-linear relationships (x², x³, etc.)

- **Logistic Regression** — despite the name, this is a **classification** algorithm; predicts probability of belonging to a category (yes/no).

### Cost Function / Loss Function
Measures how wrong the model's predictions are overall.
- High cost → low accuracy
- Low cost → high accuracy

Training = adjusting parameters (like m and c) to minimize the cost function.

### MSE (Mean Squared Error)
```
MSE = (1/n) × Σ (actual − predicted)²
```
Squaring prevents errors from cancelling out and penalizes larger errors more heavily.

---

## 10. train_test_split & random_state

```python
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
```

- **train_test_split** — splits the dataset into training and testing sets (e.g., 80/20).
- **random_state** — a seed value controlling how data is shuffled before splitting. Fixing it (e.g., `random_state=42`) makes the split reproducible — same split every time the code runs.

---

## Quick Recap Map

```
ML = Data + Algorithm
   ├── Features (input/X) + Target (output/y)
   ├── Types: Supervised | Unsupervised | Semi-Supervised | Reinforcement
   └── Lifecycle: Problem → Collect → Preprocess → Feature Engineer →
                  Split → Select Model → Train → Evaluate → Tune →
                  Deploy → Monitor → Retrain

Along the way: encode text → scale numbers → watch loss/epoch/learning rate →
minimize the cost function (MSE) → always fix random_state for reproducible splits.
```

In [7]:
df = pd.read_csv("student_study_marks.csv") # read csv file

In [8]:
df.head()

   StudyHours  Marks
0         1.0     27
1         1.2     31
2         1.2     28
3         1.3     33
4         1.4     25

In [9]:
df.shape # row 100 and column 2

(100, 2)

In [10]:
# data split
x=df[["StudyHours"]] # input = 2D
y=df["Marks"] # output = 1D

In [11]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42) # 80% training and 20% testing

In [12]:
y_test

83     99
53     68
70     87
45     57
44     59
39     57
22     41
80     90
10     33
0      27
18     32
30     48
73     92
33     51
90    100
4      25
76     92
77     91
12     44
31     51
Name: Marks, dtype: int64

In [13]:
# algorithm choose Linear
# class LinearRegression
model = LinearRegression()  # initialisation of class model object contructor

In [14]:
model.fit(X_train,y_train) # fit = data for model training

LinearRegression()

In [15]:
# y = mx + c  --- m and c get values

model.intercept_

19.053412338171313

In [16]:
model.coef_

array([8.99561772])

In [17]:
y_pred = model.predict(X_test)

In [18]:
result = pd.DataFrame({
    "actual":y_test.values,
    "predict":y_pred
})
result

    actual     predict
0       99   93.717039
1       68   69.428872
2       87   85.620983
3       57   59.533692
4       59   58.634130
5       57   54.136321
6       41   42.442018
7       90   91.018354
8       33   34.345962
9       27   28.049030
10      32   39.743333
11      48   49.638513
12      92   87.420107
13      51   51.437636
14     100  100.913534
15      25   31.647277
16      92   89.219231
17      91   90.118792
18      44   36.145086
19      51   50.538074

In [19]:
mse = mean_squared_error(y_test,y_pred)
mse

# model = 12 = decrease m and c value change

# 3 ways for error measurement 
# 1. mse
# 2. rmse = square root
# 3. mae = avg actual-pred = sum / no element

# r2 score // model doesnot have any accuracy method 
# accuracy = 95 # 100 answer = p95

12.59448267539147

In [20]:
from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(y_test,y_pred)
rmse

3.5488706197030444

In [21]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
mae

2.632422817463621

In [22]:
from sklearn.metrics import r2_score
r2 = r2_score (y_test,y_pred)
r2

0.9798410866966651

In [23]:
# generalization
hours = float (input("Enter yout study hours: "))

# Generalization, RMSE, MAE & R² Score

## Generalization
**Generalization** = how well a model performs on **new, unseen data**, not just the data it was trained on.

- Good generalization → model learns the real pattern, works well on both training and test data.
- **Overfitting** → model memorizes training data (including noise) → great on training, poor on new data → bad generalization.
- **Underfitting** → model too simple to capture the pattern → poor on both training and test data.

This is why we do the train-test split — the test set acts as a proxy for "new data" to measure generalization.

---

## RMSE (Root Mean Squared Error)
```
RMSE = √( (1/n) × Σ (actual − predicted)² )
```
- Square root of MSE, same unit as the target (e.g. ₹ if predicting price).
- Squares errors first → large errors punished more heavily → sensitive to outliers.
- Lower RMSE = better fit.

## MAE (Mean Absolute Error)
```
MAE = (1/n) × Σ |actual − predicted|
```
- Average of absolute differences between actual and predicted values.
- All errors treated equally — less sensitive to outliers than RMSE.
- Easy to interpret: "on average, predictions are off by X."

## R² Score (Coefficient of Determination)
```
R² = 1 − ( Σ(actual − predicted)² / Σ(actual − mean of actual)² )
```
- Tells you how much of the variation in the target the model explains, vs. just predicting the average every time.
- **R² = 1** → perfect predictions
- **R² = 0** → model no better than predicting the average
- **R² < 0** → model worse than predicting the average
- Example: R² = 0.85 → model explains 85% of the variation in the target.

---

### Quick Comparison

| Metric | What it tells you | Sensitive to outliers? | Same unit as target? |
|---|---|---|---|
| RMSE | Typical error size, penalizes big misses | Yes | Yes |
| MAE | Average error size | No (less) | Yes |
| R² | % of variance explained | Moderately | No (ratio, 0–1) |

In [24]:
newdata = pd.DataFrame({
    "StudyHours":[hours]
})

In [25]:
mynewdata = model.predict(newdata)
print(mynewdata[0])

# api = json - key and value

32.546838916129765

In [26]:
# new dataset = cleaning process - clean - model linear regression = 500 data

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

In [32]:
df = pd.read_csv("temperature_linear_regression_data.csv")

In [33]:
# CLEAN
# Drop exact duplicate rows
df = df.drop_duplicates()

In [34]:
print("Missing values per column:\n", df.isna().sum())

Missing values per column:
 Temperature_C     15
IceCream_Sales    15
dtype: int64

In [35]:
# Drop rows missing the target (IceCream_Sales) — can't use these to train
df = df.dropna(subset=["IceCream_Sales"])
 
# Impute missing Temperature_C with the column median (robust to outliers)
temp_median = df["Temperature_C"].median()
df["Temperature_C"] = df["Temperature_C"].fillna(temp_median)
 
# Sanity checks: remove any physically impossible values (negative temp/sales)
df = df[(df["Temperature_C"] >= -50) & (df["IceCream_Sales"] >= 0)]
 
# Reset index after cleaning
df = df.reset_index(drop=True)
 
print(f"\nCleaned shape: {df.shape}")
df.to_csv("temperature_linear_regression_data_cleaned.csv", index=False)

Cleaned shape: (477, 2)

In [36]:
# TRAIN LINEAR REGRESSION

X = df[["Temperature_C"]]
y = df["IceCream_Sales"]
 
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
 
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [37]:
model.coef_

array([10.181905])

In [38]:
model.intercept_

-54.86966825762116

In [39]:
# EVALUATE
y_pred = model.predict(X_test)
 
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
 
print("\n--- Model Results ---")
print("MSE",mse)
print("MAE",mae)
print("RMSE",rmse)
print("R2",r2)

--- Model Results ---
MSE 2269.419278110527
MAE 20.64921130035769
RMSE 47.638422288217384
R2 0.7695989133747476

In [41]:
# api = prompt - url - call // pickle / joblib - url
# AI - frontend website - enter your study hours = 
# model = output
# 1. html css js
# 2. reast js / tailwind css

In [42]:
# classification - hour = marks//number
# 3 = pass/ fail --- class/ category
# study hours - features/ input
# result -- target / output
# pass/ fail output - label
# two types of classification - 1. binary classsification - when we have 2 options pass or fail
# 2. multiclass classification - more than 2 options

# validation data - training data - learn - data
# to validate data after training by created layer for validation data then the data goes for testing 
# it will never go directly for testing without validation data
                # testing data - check - final output

In [43]:
# confusion matrix

# y_pred     y 
    # accuracy = confusion matrix tp 2 fn 2 fp 2 tn 2
    # accuracy = TP+TN/TP+TN+FP+FN
                # 2+2 / 8
                # 4/8 = 0.5 percent
# actual     predict
# pass       pass
# pass       fail
# fail       pass
# fail       fail
# pass       pass
# pass       fail
# fail       pass
# fail       fail

# 1. true positive - TP ----csv pass model pass
# 2. true negative - TN ----csv fail model fail
# 3. false positive - FP -----csv fail model pass
# 4. false negative - FN -----csv pass model fail 

# 1. model true actual true
# 2. model false actual false
# 3. model true actual False
# 4. model false actual true

In [ ]:
# hyperparameter tuning

1. accuracy = tp+tn/tp+tn+fp+fn
2. precision = tp/tp+fp  --- model % positive from that how many actual positive
eg : 10 data and model gave result that 8 students pass in exam but in actual data , there are 6 students who pass the exam
3. recall = tp/tp+fn  --- actual data = model positive
eg :  you got fail in exam then we gave for rechecking and then result will be pass --- just to recheck the data 
4. f1 score = 2 * (precision*recall / precision+recall) ---- compare f1 score to r2 score , how model understands data pattern
f1 score is minimum greater than 0.5
and standard score is greater than 0.7
r2 - high - accuracy performance better
5. z = wx + b
z = row score , w = weight , x = input , b = bias/ intercepted
6. sigmoid convert z value into range of 0 to 1 ---- sigma(z) = 1/1+e^-z
7. gradient decent/ adam - optimizor
8. probability
9. threshold value